### ISSUE TITLE
Please clarify the version of eigen

### ISSUE THREAD

**Issue by amiltonwong** [puzzlepaint/surfelmeshing#1]
Hi, @puzzlepaint ,

Thanks for releasing such surfelmeshing. For required packages such as Eigen, do you mean the development version is `the unstable source code from the development branch` ([link](http://bitbucket.org/eigen/eigen/get/default.zip))

THX!

**Comment by puzzlepaint** [comment]
Hi, I think that I used the version from the master branch at https://github.com/eigenteam/eigen-git-mirror . However, there have been two new releases in the last two days, and the [changelog](http://eigen.tuxfamily.org/index.php?title=ChangeLog) of the first one mentions "Fixes for NVCC 9". So perhaps using an unstable version is no longer necessary for CUDA 9.1 compatibility.

**Comment by puzzlepaint** [comment]
I updated the README to also point to the new Eigen release. I hope that this and the answer above fixes this issue.
