### ISSUE TITLE
 triangle mesh speed

### ISSUE THREAD

**Issue by shuochen365** [puzzlepaint/surfelmeshing#12]
Hi, I found that the speed of triangle mesh for 640 * 480 resolution image is relatively slow. Is there any other way to improve triangle mesh speed besides reducing image resolution.

**Comment by puzzlepaint** [comment]
You could try tuning the `--max_surfels_per_node` parameter to perhaps increase the performance slightly, however I would not expect large differences. Other than that, I can't think of any easy and generic changes unfortunately. In some cases, one might for example want to replace the octree with a simple grid for faster spatial access, but that depends on whether the grid would be suitable for the data, and I am also not sure how much effect that would have on the performance.

**Comment by shuochen365** [comment]
thank you very much.
