### ISSUE TITLE
QCoreApplication Event Error

### ISSUE THREAD

**Issue by glubiana** [puzzlepaint/surfelmeshing#14]
Hi,
I'm trying to launch surfelmeshing on a windows machine with the subsequent command

`./build_RelWithDebInfo/applications/surfel_meshing/SurfelMeshing /path/to/some_tum_rgbd_dataset groundtruth.txt --follow_input_camera false`

using the TUM RGB-D benchmark sample data, but I get this error from QT

`ASSERT failure in QCoreApplication::sendEvent: "Cannot send events to objects owned by a different thread. Current thread 0x0x174b485e370. Receiver '' (of type 'QOffscreenSurface') was created in thread 0x0x174b4899af0"`

when `exec` si called on `QApplication`.

 Is there the possibility that I'm doing something wrong?

**Comment by puzzlepaint** [comment]
Is this resolved? If yes, do you know what fixed it? That might help others who encounter the same problem.

**Comment by zhuisa** [comment]
@glubiana Hi！I encounter the same problem. Can you give me some help! Thanks!
