### ISSUE TITLE
the format of input depth images

### ISSUE THREAD

**Issue by tftangming** [puzzlepaint/surfelmeshing#19]
I want to use the program to serve as the back-end in order to generate a mesh, and I want to know whether all the type include as follow can be support?
`enum class ImageType {
  U8 = 0,
  U16,
  U32,
  U64,
  I8,
  I16,
  I32,
  I64,
  Vec2u8,
  Vec3u8,
  Vec4u8,
  Float,
  Double,
  Invalid
};`

**Comment by puzzlepaint** [comment]
The program supports the format of the TUM RGB-D benchmark, as described in the Readme. This means that the depth images must be saved as 16 bit PNGs. If you have a different format, you could convert it to 16 bit PNGs. Some of the formats you listed do not seem to make sense as depth input formats, however.
