### ISSUE TITLE
error: ‘::isnan’ has not been declared

### ISSUE THREAD

**Issue by RuibinMa** [puzzlepaint/surfelmeshing#4]
Hello,
Thanks for sharing the code. I met the following error when I tried to compile your code:

.../surfelmeshing/libvis/src/libvis/patch_match_stereo.cc:782:18: error: ‘::isnan’ has not been declared
             if (!::isnan(proposal_costs) && !(proposal_costs >= costs(x, y))) {

I'm using gcc-5. I have found by google that this might be caused by missing "-std=c++11" flags. However, I found these flags in the CMakeList.txt.

**Comment by puzzlepaint** [comment]
Does it work if you use `std::isnan` instead of `::isnan`?

**Comment by RuibinMa** [comment]
Yeah, it works. Thank you!
